export const officialStoreSlug = "msm-my-store-oficial-segundo-frente";

export const officialStoreFallback = {
  id: "demo-msm-store",
  name: "MSM my store",
  slug: officialStoreSlug,
  type: "tienda_oficial",
  status: "activo",
  owner_name: "Miguel Soria Martinez",
  company_name: "MSM MY STORE LLC",
  phone: "+1 772 301 5523",
  whatsapp: "+1 772 301 5523",
  email: "commercial@msmmystore.com",
  province: "Santiago de Cuba",
  municipality: "Segundo Frente",
  address: "Mayari Arriba y Segundo Frente",
  description:
    "MSM my store conecta la diaspora con Cuba mediante productos, servicios, remesas, pagos organizados, entregas locales, vendedores VIP y confianza centralizada.",
  warranty: "Garantia coordinada por MSM segun producto y evidencia de entrega.",
  categories: ["remesas", "cambios", "alimentos", "electrodomesticos", "energia-solar", "servicios"],
  services_active: ["remesas", "cambios", "productos", "servicios"],
  delivery_zones: ["Segundo Frente", "Mayari Arriba", "Santiago de Cuba"],
  pickup_available: true,
  delivery_available: true,
  transfer_available: true,
  remittances_active: true,
  remittance_delivery_methods: ["efectivo", "transferencia", "pickup", "domicilio"],
  remittance_municipalities: ["Segundo Frente", "Mayari Arriba"],
  cash_available: 5000,
  remittance_daily_limit: 15000,
  remittance_eta: "24h a 48h segun zona y disponibilidad",
  remittance_evidence_mode: "Foto, firma, mensaje o codigo OTP",
  reputation_label: "Tienda oficial destacada",
  is_featured: true,
  sellers: {
    level: "super_vip",
    status: "aprobado",
    daily_capacity: 30,
    max_confirm_minutes: 45
  }
};

export const officialStoreProductsFallback = [
  {
    id: "demo-freidora",
    name: "Freidora de aire EKO",
    slug: "freidora-de-aire-eko",
    price: 70,
    currency: "USD",
    stock: 6,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Mayari Arriba y Segundo Frente",
    warranty: "Garantia MSM segun disponibilidad y evidencia.",
    promised_sla: "h48",
    availability: "stock real o por confirmar",
    product_images: [{ url: "/products/msm-freidora-aire.jpg" }],
    categories: { name: "Electrodomesticos" }
  },
  {
    id: "demo-batidora",
    name: "Batidora Fagor",
    slug: "batidora-fagor",
    price: 45,
    currency: "USD",
    stock: 8,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Mayari Arriba y Segundo Frente",
    warranty: "Garantia MSM segun disponibilidad y evidencia.",
    promised_sla: "h48",
    availability: "stock real",
    product_images: [{ url: "/products/msm-batidora.jpg" }],
    categories: { name: "Electrodomesticos" }
  },
  {
    id: "demo-lavadora",
    name: "Lavadora semidoble EKO",
    slug: "lavadora-semidoble-eko",
    price: 198,
    currency: "USD",
    stock: 3,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Mayari Arriba y Segundo Frente",
    warranty: "Garantia MSM segun disponibilidad y evidencia.",
    promised_sla: "h72",
    availability: "stock real o por confirmar",
    product_images: [{ url: "/products/msm-lavadora.jpg" }],
    categories: { name: "Electrodomesticos" }
  },
  {
    id: "demo-cocina",
    name: "Cocina infrarroja EKO2202",
    slug: "cocina-infrarroja-eko2202",
    price: 45,
    currency: "USD",
    stock: 10,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Mayari Arriba y Segundo Frente",
    warranty: "Garantia MSM segun disponibilidad y evidencia.",
    promised_sla: "h48",
    availability: "stock real",
    product_images: [{ url: "/products/msm-cocina-infrarroja.jpg" }],
    categories: { name: "Electrodomesticos" }
  },
  {
    id: "demo-nevera",
    name: "Nevera 3.5 pies gris perlado",
    slug: "nevera-35-pies-gris-perlado",
    price: 255,
    currency: "USD",
    stock: 2,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Mayari Arriba y Segundo Frente",
    warranty: "Garantia MSM segun disponibilidad y evidencia.",
    promised_sla: "bajo_gestion",
    availability: "por confirmar",
    product_images: [{ url: "/products/msm-nevera-35.jpg" }],
    categories: { name: "Electrodomesticos" }
  },
  {
    id: "demo-freezer",
    name: "Freezer 7 pies EKO",
    slug: "freezer-7-pies-eko",
    price: 320,
    currency: "USD",
    stock: 4,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Mayari Arriba y Segundo Frente",
    warranty: "Garantia MSM segun disponibilidad y evidencia.",
    promised_sla: "bajo_gestion",
    availability: "por confirmar",
    product_images: [{ url: "/products/msm-freezer-7.jpg" }],
    categories: { name: "Electrodomesticos" }
  },
  {
    id: "demo-olla",
    name: "Olla reina EKO",
    slug: "olla-reina-eko",
    price: 36,
    currency: "USD",
    stock: 12,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Mayari Arriba y Segundo Frente",
    warranty: "Garantia MSM segun disponibilidad y evidencia.",
    promised_sla: "h48",
    availability: "stock real",
    product_images: [{ url: "/products/msm-olla-reina.jpg" }],
    categories: { name: "Electrodomesticos" }
  },
  {
    id: "demo-televisor",
    name: "Televisor smart MSM",
    slug: "televisor-smart-msm",
    price: 280,
    currency: "USD",
    stock: 2,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Mayari Arriba y Segundo Frente",
    warranty: "Garantia MSM segun disponibilidad y evidencia.",
    promised_sla: "bajo_gestion",
    availability: "por confirmar",
    product_images: [{ url: "/brand/msm-my-store-logo.jpeg" }],
    categories: { name: "Electrodomesticos" }
  },
  {
    id: "demo-ventilador-recargable",
    name: "Ventilador recargable",
    slug: "ventilador-recargable",
    price: 55,
    currency: "USD",
    stock: 5,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Mayari Arriba y Segundo Frente",
    warranty: "Garantia MSM segun disponibilidad y evidencia.",
    promised_sla: "h48",
    availability: "stock real o por confirmar",
    product_images: [{ url: "/brand/msm-my-store-logo.jpeg" }],
    categories: { name: "Electrodomesticos" }
  },
  {
    id: "demo-leche-polvo",
    name: "Leche en polvo",
    slug: "leche-en-polvo",
    price: 18,
    currency: "USD",
    stock: 20,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Mayari Arriba y Segundo Frente",
    warranty: "Entrega documentada por MSM.",
    promised_sla: "h48",
    availability: "stock real o por confirmar",
    product_images: [{ url: "https://images.unsplash.com/photo-1542838132-92c53300491e" }],
    categories: { name: "Alimentos" }
  },
  {
    id: "demo-cambio-divisas-segundo-frente",
    name: "Servicio de cambio de divisas Segundo Frente",
    slug: "cambio-divisas-segundo-frente",
    price: 1,
    currency: "USD",
    stock: 999,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Segundo Frente y Mayari Arriba",
    warranty: "Operacion sujeta a revision economica MSM.",
    promised_sla: "h24",
    availability: "activo por zona",
    product_images: [{ url: "/brand/msm-my-store-logo.jpeg" }],
    categories: { name: "Cambios" }
  },
  {
    id: "demo-remesa-segundo-frente",
    name: "Servicio de remesa efectivo Segundo Frente",
    slug: "remesa-efectivo-segundo-frente",
    price: 1,
    currency: "USD",
    stock: 999,
    province: "Santiago de Cuba",
    municipality: "Segundo Frente",
    delivery_zone: "Segundo Frente y Mayari Arriba",
    warranty: "Evidencia por foto, firma, mensaje o codigo OTP.",
    promised_sla: "h24",
    availability: "activo por zona",
    product_images: [{ url: "/brand/msm-my-store-logo.jpeg" }],
    categories: { name: "Remesas" }
  }
];

export const officialPublicProductsFallback = officialStoreProductsFallback.map((product) => ({
  id: product.id,
  name: product.name,
  slug: product.slug,
  price: product.price,
  currency: product.currency,
  stock: product.stock,
  category: Array.isArray(product.categories) ? product.categories[0]?.name : product.categories.name,
  store: officialStoreFallback.name,
  storeSlug: officialStoreFallback.slug,
  country: "Cuba",
  province: product.province,
  municipality: product.municipality,
  deliveryZone: product.delivery_zone,
  warranty: product.warranty,
  promisedSla: product.promised_sla,
  availability: product.availability,
  image: product.product_images[0]?.url ?? "/brand/msm-my-store-logo.jpeg"
}));
