with province_rows(name) as (
  values
    ('Pinar del Rio'),
    ('Artemisa'),
    ('La Habana'),
    ('Mayabeque'),
    ('Matanzas'),
    ('Villa Clara'),
    ('Cienfuegos'),
    ('Sancti Spiritus'),
    ('Ciego de Avila'),
    ('Camaguey'),
    ('Las Tunas'),
    ('Holguin'),
    ('Granma'),
    ('Santiago de Cuba'),
    ('Guantanamo'),
    ('Isla de la Juventud')
),
inserted_provinces as (
  insert into provinces (name)
  select name from province_rows
  on conflict (name) do nothing
  returning id, name
),
all_provinces as (
  select id, name from inserted_provinces
  union
  select id, name from provinces where name in (select name from province_rows)
),
municipality_rows(province_name, name) as (
  values
    ('Pinar del Rio', 'Consolacion del Sur'),
    ('Pinar del Rio', 'Guane'),
    ('Pinar del Rio', 'La Palma'),
    ('Pinar del Rio', 'Los Palacios'),
    ('Pinar del Rio', 'Mantua'),
    ('Pinar del Rio', 'Minas de Matahambre'),
    ('Pinar del Rio', 'Pinar del Rio'),
    ('Pinar del Rio', 'San Juan y Martinez'),
    ('Pinar del Rio', 'San Luis'),
    ('Pinar del Rio', 'Sandino'),
    ('Pinar del Rio', 'Vinales'),
    ('Artemisa', 'Alquizar'),
    ('Artemisa', 'Artemisa'),
    ('Artemisa', 'Bahia Honda'),
    ('Artemisa', 'Bauta'),
    ('Artemisa', 'Caimito'),
    ('Artemisa', 'Candelaria'),
    ('Artemisa', 'Guanajay'),
    ('Artemisa', 'Guira de Melena'),
    ('Artemisa', 'Mariel'),
    ('Artemisa', 'San Antonio de los Banos'),
    ('Artemisa', 'San Cristobal'),
    ('La Habana', 'Arroyo Naranjo'),
    ('La Habana', 'Boyeros'),
    ('La Habana', 'Centro Habana'),
    ('La Habana', 'Cerro'),
    ('La Habana', 'Cotorro'),
    ('La Habana', 'Diez de Octubre'),
    ('La Habana', 'Guanabacoa'),
    ('La Habana', 'Habana del Este'),
    ('La Habana', 'Habana Vieja'),
    ('La Habana', 'La Lisa'),
    ('La Habana', 'Marianao'),
    ('La Habana', 'Playa'),
    ('La Habana', 'Plaza de la Revolucion'),
    ('La Habana', 'Regla'),
    ('La Habana', 'San Miguel del Padron'),
    ('Mayabeque', 'Batabano'),
    ('Mayabeque', 'Bejucal'),
    ('Mayabeque', 'Guines'),
    ('Mayabeque', 'Jaruco'),
    ('Mayabeque', 'Madruga'),
    ('Mayabeque', 'Melena del Sur'),
    ('Mayabeque', 'Nueva Paz'),
    ('Mayabeque', 'Quivican'),
    ('Mayabeque', 'San Jose de las Lajas'),
    ('Mayabeque', 'San Nicolas'),
    ('Mayabeque', 'Santa Cruz del Norte'),
    ('Matanzas', 'Calimete'),
    ('Matanzas', 'Cardenas'),
    ('Matanzas', 'Cienaga de Zapata'),
    ('Matanzas', 'Colon'),
    ('Matanzas', 'Jaguey Grande'),
    ('Matanzas', 'Jovellanos'),
    ('Matanzas', 'Limonar'),
    ('Matanzas', 'Los Arabos'),
    ('Matanzas', 'Marti'),
    ('Matanzas', 'Matanzas'),
    ('Matanzas', 'Pedro Betancourt'),
    ('Matanzas', 'Perico'),
    ('Matanzas', 'Union de Reyes'),
    ('Villa Clara', 'Caibarien'),
    ('Villa Clara', 'Camajuani'),
    ('Villa Clara', 'Cifuentes'),
    ('Villa Clara', 'Corralillo'),
    ('Villa Clara', 'Encrucijada'),
    ('Villa Clara', 'Manicaragua'),
    ('Villa Clara', 'Placetas'),
    ('Villa Clara', 'Quemado de Guines'),
    ('Villa Clara', 'Ranchuelo'),
    ('Villa Clara', 'Remedios'),
    ('Villa Clara', 'Sagua la Grande'),
    ('Villa Clara', 'Santa Clara'),
    ('Villa Clara', 'Santo Domingo'),
    ('Cienfuegos', 'Abreus'),
    ('Cienfuegos', 'Aguada de Pasajeros'),
    ('Cienfuegos', 'Cienfuegos'),
    ('Cienfuegos', 'Cruces'),
    ('Cienfuegos', 'Cumanayagua'),
    ('Cienfuegos', 'Lajas'),
    ('Cienfuegos', 'Palmira'),
    ('Cienfuegos', 'Rodas'),
    ('Sancti Spiritus', 'Cabaiguan'),
    ('Sancti Spiritus', 'Fomento'),
    ('Sancti Spiritus', 'Jatibonico'),
    ('Sancti Spiritus', 'La Sierpe'),
    ('Sancti Spiritus', 'Sancti Spiritus'),
    ('Sancti Spiritus', 'Taguasco'),
    ('Sancti Spiritus', 'Trinidad'),
    ('Sancti Spiritus', 'Yaguajay'),
    ('Ciego de Avila', 'Baragua'),
    ('Ciego de Avila', 'Bolivia'),
    ('Ciego de Avila', 'Chambas'),
    ('Ciego de Avila', 'Ciego de Avila'),
    ('Ciego de Avila', 'Ciro Redondo'),
    ('Ciego de Avila', 'Florencia'),
    ('Ciego de Avila', 'Majagua'),
    ('Ciego de Avila', 'Moron'),
    ('Ciego de Avila', 'Primero de Enero'),
    ('Ciego de Avila', 'Venezuela'),
    ('Camaguey', 'Camaguey'),
    ('Camaguey', 'Carlos Manuel de Cespedes'),
    ('Camaguey', 'Esmeralda'),
    ('Camaguey', 'Florida'),
    ('Camaguey', 'Guaimaro'),
    ('Camaguey', 'Jimaguayu'),
    ('Camaguey', 'Minas'),
    ('Camaguey', 'Najasa'),
    ('Camaguey', 'Nuevitas'),
    ('Camaguey', 'Santa Cruz del Sur'),
    ('Camaguey', 'Sibanicu'),
    ('Camaguey', 'Sierra de Cubitas'),
    ('Camaguey', 'Vertientes'),
    ('Las Tunas', 'Amancio'),
    ('Las Tunas', 'Colombia'),
    ('Las Tunas', 'Jesus Menendez'),
    ('Las Tunas', 'Jobabo'),
    ('Las Tunas', 'Las Tunas'),
    ('Las Tunas', 'Majibacoa'),
    ('Las Tunas', 'Manati'),
    ('Las Tunas', 'Puerto Padre'),
    ('Holguin', 'Antilla'),
    ('Holguin', 'Baguanos'),
    ('Holguin', 'Banes'),
    ('Holguin', 'Cacocum'),
    ('Holguin', 'Calixto Garcia'),
    ('Holguin', 'Cueto'),
    ('Holguin', 'Frank Pais'),
    ('Holguin', 'Gibara'),
    ('Holguin', 'Holguin'),
    ('Holguin', 'Mayari'),
    ('Holguin', 'Moa'),
    ('Holguin', 'Rafael Freyre'),
    ('Holguin', 'Sagua de Tanamo'),
    ('Holguin', 'Urbano Noris'),
    ('Granma', 'Bartolome Maso'),
    ('Granma', 'Bayamo'),
    ('Granma', 'Buey Arriba'),
    ('Granma', 'Campechuela'),
    ('Granma', 'Cauto Cristo'),
    ('Granma', 'Guisa'),
    ('Granma', 'Jiguani'),
    ('Granma', 'Manzanillo'),
    ('Granma', 'Media Luna'),
    ('Granma', 'Niquero'),
    ('Granma', 'Pilon'),
    ('Granma', 'Rio Cauto'),
    ('Granma', 'Yara'),
    ('Santiago de Cuba', 'Contramaestre'),
    ('Santiago de Cuba', 'Guama'),
    ('Santiago de Cuba', 'Mella'),
    ('Santiago de Cuba', 'Palma Soriano'),
    ('Santiago de Cuba', 'San Luis'),
    ('Santiago de Cuba', 'Santiago de Cuba'),
    ('Santiago de Cuba', 'Segundo Frente'),
    ('Santiago de Cuba', 'Songo-La Maya'),
    ('Santiago de Cuba', 'Tercer Frente'),
    ('Guantanamo', 'Baracoa'),
    ('Guantanamo', 'Caimanera'),
    ('Guantanamo', 'El Salvador'),
    ('Guantanamo', 'Guantanamo'),
    ('Guantanamo', 'Imias'),
    ('Guantanamo', 'Maisi'),
    ('Guantanamo', 'Manuel Tames'),
    ('Guantanamo', 'Niceto Perez'),
    ('Guantanamo', 'San Antonio del Sur'),
    ('Guantanamo', 'Yateras'),
    ('Isla de la Juventud', 'Isla de la Juventud')
)
insert into municipalities (province_id, name)
select p.id, m.name
from municipality_rows m
join all_provinces p on p.name = m.province_name
on conflict (province_id, name) do nothing;
